### ISSUE TITLE
install ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/opt/concourse/worker/volumes/live/369745d3-6991-42a3-71cb-795aa3d79471/volume/absl-py_1615411186320/work'

### ISSUE THREAD

**Issue by pengshuoyang** [burstein-lab/genomic-nlp#1]
I am installing this tool under python 3.7,centos 7.5,
 
When i was running "pip install -r requirements.txt", here repot a error:ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/opt/concourse/worker/volumes/live/369745d3-6991-42a3-71cb-795aa3d79471/volume/absl-py_1615411186320/work'.

After deleting all these lines,here is another error report:ERROR: Could not find a version that satisfies the requirement anaconda-client==1.7.2 (from versions: 1.1.1, 1.2.2)
ERROR: No matching distribution found for anaconda-client==1.7.2

I have checked many reports and do not know how to install this tool correctly.

**Comment by daniellemiller** [comment]
sorry for that,
I have updated the [requirements.txt](https://github.com/burstein-lab/genomic-nlp/blob/main/requirements.txt) file and tested it on both Linux & mac, it should work now LMK if not

**Comment by daniellemiller** [comment]
closing this issue for now, re-open if needed
