### ISSUE TITLE
Where can I download KO HMM database file?

### ISSUE THREAD

**Issue by zoubohao** [burstein-lab/genomic-nlp#3]
Hi  authors

This is nice work. I just wonder how I can download the KO HMM database.

Thanks for replying

**Comment by bursteinlab** [comment]
Thanks for the kind words and sorry for the late reply...

We added a link to the HMMs we used in the README file, here it is for your convenience:

[**kg.05_21.ren4prok.2.hmm.db.gz** (2.7GB)](https://drive.google.com/file/d/1am-9fxYXtoZ_RGyzJ-UXW2Qbpfv2srX1/view?usp=sharing)

**Comment by zoubohao** [comment]
Thank you.

**Comment by CCCdwf** [comment]
Is the data still there and is it possible to share it, the link provided by the author shows that the file doesn't exist anymore
